#!/usr/bin/env python3
"""
List task IDs that still need to run, grouped by array.

Usage:
    python scripts/missing_combos.py
    python scripts/missing_combos.py --grid online

Also writes a one-liner resubmission script under $SWAT_OUTPUT_DIR that
re-submits only the task IDs that are still missing, using Slurm's
--array=id1,id2,... syntax.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.attacks_online import expected_round_paths
from src.config import CONFIG, get_output_dir, online_combos


def _attack_rate_tag(rate: float) -> str:
    return "r" + f"{rate:.4f}".rstrip("0").rstrip(".").replace(".", "p")


def clean_missing_task_ids(out_dir: Path) -> list[int]:
    ids = []
    d = out_dir / "checkpoints" / "clean"
    for i, m in enumerate(CONFIG["MODELS"]):
        for j, s in enumerate(CONFIG["SEEDS"]):
            task_id = i * len(CONFIG["SEEDS"]) + j
            if not (d / f"{m}__{s}.json").exists():
                ids.append(task_id)
    return ids


def attack_missing_task_ids(out_dir: Path, attack: str) -> list[int]:
    """
    A task is 'missing' if any of its 4 rate JSONs is missing. That way a
    partial-task resubmission finishes the remaining rates (run_attack.py
    skips finished rates internally).
    """
    ids = []
    d = out_dir / "checkpoints" / "attacks" / attack
    for i, m in enumerate(CONFIG["MODELS"]):
        for j, s in enumerate(CONFIG["SEEDS"]):
            task_id = i * len(CONFIG["SEEDS"]) + j
            missing = False
            for r in CONFIG["POISON_RATES"]:
                tag = _attack_rate_tag(r)
                if not (d / f"{m}__{s}__{tag}.json").exists():
                    missing = True
                    break
            if missing:
                ids.append(task_id)
    return ids


def online_missing_task_ids() -> list[int]:
    ids = []
    for task_id, combo in enumerate(online_combos()):
        paths = expected_round_paths(
            combo["detector"], combo["generator"], combo["T"],
            combo["delta_p"], combo["seed"],
        )
        if not all(p.exists() for p in paths):
            ids.append(task_id)
    return ids


def write_script(path: Path, lines: list[str]) -> None:
    path.write_text("\n".join(lines) + "\n")
    path.chmod(0o755)
    print(f"\nResubmit script: {path}")


def _array_spec(ids: list[int]) -> str:
    """Compact [0,1,2,5] -> '0-2,5' for Slurm --array."""
    if not ids:
        return ""
    ids = sorted(set(ids))
    spans = []
    start = prev = ids[0]
    for x in ids[1:]:
        if x == prev + 1:
            prev = x
            continue
        spans.append(f"{start}-{prev}" if start != prev else str(start))
        start = prev = x
    spans.append(f"{start}-{prev}" if start != prev else str(start))
    return ",".join(spans)


def report_main_grid(out: Path) -> None:
    clean_missing = clean_missing_task_ids(out)
    print(f"Clean array — missing task IDs: {len(clean_missing)} / {len(CONFIG['MODELS']) * len(CONFIG['SEEDS'])}")
    if clean_missing:
        print(f"  {_array_spec(clean_missing)}")

    lines = [
        "#!/bin/bash",
        "# Auto-generated by scripts/missing_combos.py — resubmits only the",
        "# task IDs that are still missing output JSONs.",
        "set -e",
        "",
    ]
    if clean_missing:
        lines.append(f"sbatch --array={_array_spec(clean_missing)} slurm/10_clean_baselines.sh")

    for atk, script in [
        ("random_flip",   "slurm/20_attack_random_flip.sh"),
        ("targeted_flip", "slurm/21_attack_targeted_flip.sh"),
        ("feature_noise", "slurm/22_attack_feature_noise.sh"),
    ]:
        ids = attack_missing_task_ids(out, atk)
        print(f"{atk:<14} array — missing task IDs: {len(ids)} / 36")
        if ids:
            print(f"  {_array_spec(ids)}")
            lines.append(f"sbatch --array={_array_spec(ids)} {script}")

    write_script(out / "resubmit.sh", lines)


def report_online_grid(out: Path) -> None:
    ids = online_missing_task_ids()
    n_total = len(online_combos())
    print(f"Online array — missing task IDs: {len(ids)} / {n_total}")
    if ids:
        print(f"  {_array_spec(ids)}")

    lines = [
        "#!/bin/bash",
        "# Auto-generated by scripts/missing_combos.py --grid online.",
        "set -e",
        "",
    ]
    if ids:
        lines.append(f"sbatch --array={_array_spec(ids)} slurm/40_online_retraining.sh")
    write_script(out / "resubmit_online.sh", lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--grid", choices=["main", "online", "both"], default="main",
                    help="Which experiment grid to inspect. Default: main.")
    args = ap.parse_args()

    out = get_output_dir()
    if args.grid in ("main", "both"):
        report_main_grid(out)
    if args.grid in ("online", "both"):
        report_online_grid(out)


if __name__ == "__main__":
    main()
