#!/bin/bash
# One-command launch of the full AE + LSTM-AE HPO chain (all 4 stages each).
#
# Submits:
#   AE chain:      Stage1 → Gate91 → Stage2 → Gate92 → Stage3 → Gate93 → Final
#   LSTM-AE chain: Stage1 → Gate94 → Stage2 → Gate95 → Stage3 → Gate96 → Final
#
# The two chains run in parallel. Each stage's array runs once its preceding
# gate finishes (gates use --dependency=afterany so a few failed tasks don't
# block the chain — the gate's own success-threshold check decides whether to
# abort).
#
# Run this once from the login node; the queue will progress on its own.
#
# Usage:
#   bash scripts/submit_full_hpo.sh         # both detectors
#   bash scripts/submit_full_hpo.sh ae      # AE chain only
#   bash scripts/submit_full_hpo.sh lstm    # LSTM-AE chain only

set -euo pipefail

cd "$(dirname "$0")/.."   # project root

WHICH=${1:-both}

# Sanity: env vars
: "${SWAT_DATA_DIR:?Export SWAT_DATA_DIR before submitting.}"
: "${SWAT_OUTPUT_DIR:?Export SWAT_OUTPUT_DIR before submitting.}"
mkdir -p logs

# Generate Stage 1 manifests immediately (Stages 2-3-Final manifests will be
# generated by their preceding gate jobs).
python scripts/make_hpo_manifests.py --stage ae_stage1
python scripts/make_hpo_manifests.py --stage lstm_ae_stage1
echo

submit_ae_chain() {
    echo "─── Submitting AE chain ──────────────────────────────────────────"
    local s1=$(sbatch --parsable slurm/50_ae_hpo_stage1.sh)
    echo "  AE Stage 1 (192 tasks)        : $s1"
    local g1=$(sbatch --parsable --dependency=afterany:$s1 \
        slurm/91_gate_ae_s1_to_s2.sh)
    echo "  AE Gate S1→S2                 : $g1 (afterany:$s1)"
    echo "  Subsequent stages (S2, gate S2→S3, S3, gate S3→Final, Final)"
    echo "  will be submitted automatically by gate jobs as they fire."
    echo
}

submit_lstm_chain() {
    echo "─── Submitting LSTM-AE chain ─────────────────────────────────────"
    local s1=$(sbatch --parsable slurm/60_lstm_ae_hpo_stage1.sh)
    echo "  LSTM-AE Stage 1 (72 tasks)    : $s1"
    local g1=$(sbatch --parsable --dependency=afterany:$s1 \
        slurm/94_gate_lstm_s1_to_s2.sh)
    echo "  LSTM-AE Gate S1→S2            : $g1 (afterany:$s1)"
    echo "  Subsequent stages will be submitted automatically by gate jobs."
    echo
}

case "$WHICH" in
    ae)    submit_ae_chain ;;
    lstm)  submit_lstm_chain ;;
    both)  submit_ae_chain; submit_lstm_chain ;;
    *)
        echo "Usage: $0 [ae|lstm|both]" >&2
        exit 2
        ;;
esac

echo "─── Done ─────────────────────────────────────────────────────────"
echo "Watch progress with:  squeue -u \$USER"
echo "Inspect a finished stage's CSV:  cat \$SWAT_OUTPUT_DIR/hpo/results/<stage>.csv | head"
echo "Find errors:  find \$SWAT_OUTPUT_DIR/hpo/results -name '*.error.json'"
